- Makefile
This reverts commit dce155a3cf535592fb8606a81e270fff4170dd0e.
> Revert "Makefile: optimize build for local cpu"

- libs2eplugins/src/s2e/Plugins/ExecutionTracers/TestCaseGenerator.cpp
- libs2eplugins/src/s2e/Plugins/ExecutionTracers/TestCaseGenerator.h
Add an option ".generateOnStateFork" to the test-case generator (default false).
If enabled, a new test case with suffix "fork" is generated for each newly
forked execution state.
> libs2eplugins: optionally create test cases when forking states

- klee/lib/Core/ExecutionState.cpp
There is a duplicate for-loop in the klee::ExecutionState::merge function when merging memory objects. 
Signed-off-by: Zhongjie Wang <wzj401@gmail.com>
> klee: Cleaned duplicate code block in ExecutionState::merge

- Makefile
There is a bug in the version of soci used,
which is raised by recent versions of compilers
and fixed in the repo of soci.
The issue:
ordered comparison between pointer and zero ('int *' and 'int'):
src/backends/mysql/session.cpp:
if (port < 0)
{
throw soci_error(err);
}
This patch uses soci v4.0.1 (334cc55)
> Using soci 4.0.1

- klee/lib/Solver/SolverFactory.cpp
There was a missing slash, s2e-lastsolver.log.
Signed-off-by: Vitaly Chipounov <vitaly@cyberhaven.com>
> klee: fixed path to solver logs

- scripts/determine_clang_binary_suffix.py
* Distro/Verision: Ubuntu 20.04.3 LTS
* `distro.linux_distribution()` is deprecated, which causes build failure on newer ubuntu installation.
This PR fixes the issue.
```
$ s2e build
INFO: [build] Building S2E (release) in /home/aesophor/s2e/build
INFO: [sh.command] <Command '/usr/bin/make --directory=/home/aesophor/s2e/build --file=/home/aesophor/s2e/source/Makefile install', pid 52599>: process started
make: Entering directory '/home/aesophor/s2e/build'
/home/aesophor/s2e/source/scripts//..//s2e/Makefile:84: *** "Failed to determine Clang binary to download: /home/aesophor/s2e/source/s2e//..//s2e/scripts/determine_clang_binary_suffix.py:84: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's …
```
> replace `distro.linux_distribution()` with `distro.{name,version}()`

- klee/lib/Core/Executor.cpp
Since S2E requires C++17, we should prefer `nullptr` to `0`.
Signed-off-by: Marco Wang <m.aesophor@gmail.com>
> klee/Executor: use nullptr instead of 0

- guest/common/include/s2e/s2e.h
- klee/include/klee/Executor.h
- klee/include/klee/util/Assignment.h
- klee/lib/Core/Executor.cpp
- libs2ecore/include/s2e/S2EExecutor.h
- libs2ecore/src/S2EExecutor.cpp
- libs2eplugins/src/s2e/Plugins/Core/BaseInstructions.cpp
- testsuite/basic10-fork-no-constraint/Makefile
- testsuite/basic10-fork-no-constraint/config.yml
- testsuite/basic10-fork-no-constraint/main.c
- testsuite/basic10-fork-no-constraint/run-tests.tpl
As discussed in [1] and [2], it would be useful if the user can
fork a state unconditionally in their plugin code and switch back to it later.
This commit introduces a new way to fork a state without specifying
symbolic conditions. Essentially, an overloaded version of
`klee::Executor::fork()` is added which works similarly to
the regular version but without any path constraint code.
Besides, an overloaded version of `S2EExecutor::fork()` is added,
so that when the user explicitly forks a state using the new API,
S2E can write debugging messages just like the regular version of
`S2EExecutor::fork()` does.
Finally, since the two versions of `S2EExecutor::fork()` shares
a lot of similarity, the actual forking work has been moved to
`S2EExecutor::doFork()` in order to avoid code duplication. …
> klee,s2e: added support for fork() without symbolic conditions 

- klee/include/klee/util/Ref.h
This was implemented last year in upstream (https://github.com/klee/klee/commit/c763a4087f1d8fa4dbdfb9c8f30d545cdb66a0aa), which allows us to:
1. easily test whether a `klee::ref` holds a nullptr
2. do something like:
```cpp
if (ref<ConstantExpr> ce = dyn_cast<ConstantExpr>(expr)) {
// Do something with `ce`
}
```
> klee/Ref: implemented operator bool()

- libs2ecore/src/S2EExecutor.cpp
Signed-off-by: Vitaly Chipounov <vitaly@cyberhaven.com>
> s2e/executor: fixed crash caused by uninitialized vector

- libs2ecore/src/S2EExecutionState.cpp
> libs2ecore: reuse `pointerSize` argument

- Makefile
Without specifying the output filename, wget may saves the downloaded file to
a file with an unexpected name (e.g., when the file is hosted on AWS), which
leads to build failure.
This patch enforces wget to save downloaded files to files with desired names.
> Specify the output file name for wget command

- libs2ecore/include/s2e/CorePlugin.h
- libs2ecore/include/s2e/S2EExecutor.h
- libs2ecore/src/S2EExecutor.cpp
- libs2eplugins/src/s2e/Plugins/Lua/LuaCoreEvents.cpp
- libs2eplugins/src/s2e/Plugins/Lua/LuaCoreEvents.h
- libs2eplugins/src/s2e/Plugins/PathLimiters/ForkLimiter.cpp
- libs2eplugins/src/s2e/Plugins/PathLimiters/ForkLimiter.h
- libs2eplugins/src/s2e/Plugins/PathLimiters/ResourceMonitor.cpp
- libs2eplugins/src/s2e/Plugins/PathLimiters/ResourceMonitor.h
This gives the user the ability to inspect the branch condition
before they decide whether the state fork should be allowed.
Signed-off-by: Marco Wang \<m.aesophor@gmail.com>
> libs2ecore,libs2eplugins: emit condition onStateForkDecide

- libs2eplugins/src/s2e/Plugins/OSMonitors/Support/IntervalMapWrapper.h
The llvm::IntervalMap's allocator is now destroyed after the IntervalMap itself.
Signed-off-by: Marco Wang \<m.aesophor@gmail.com>
> libs2eplugins/IntervalMapWrapper: remove outdated comment

- libs2ecore/include/s2e/S2EExecutionState.h
Because it is not used anymore.
> libs2ecore/S2EExecutionState: remove makeSymbolic()

- libs2ecore/src/S2EExecutionState.cpp
Using push_back() excessively can lead to frequent reallocation
and unneeded copying of the underlying array.
Thanks!
> libs2ecore/S2EExecutionState: avoid excessive push_back()

- libtcg/src/tcg.c
Adding an element using g_array_append_val() may cause re-allocation
of the underlying array to accommodate the inserted element. However,
helper_table stores the pointer to the element in the underlying
array of garray (i.e., TCGHelperInfo*) as the value. If the
underlying array is re-allocated, accessing through helper_table may
cause the dereference of a wild pointer and further the crash/dead
loop of S2E.
To fix this bug, we just allocate the memory for TCGHelperInfo* helper
ourselves to avoid using the pointer to the private data field of
garray. After the fix, s_additional_helpers will store pointers
instead of instances of TCGHelperInfo.
> libtcg: fix use after free bug in tcg_register_helper()

- Dockerfile
- Makefile
Adds support for building S2E against a binary distribution of Z3
and makes it the default option.
The dockerfile is updated to install libgomp1 and unzip (to run and
install a binary Z3 distribution), and to download and install a
recent version of CMake, which was necessary to build LLVM 13 from
source, so that these changes could be tested.
> makefile,dockerfile: Support using binary Z3 distributions

- libtcg/include/tcg/tcg-op.h
Host OS: Ubuntu 20.04.4 LTS
This PR resolves a symbol lookup error mentioned in: https://groups.google.com/g/s2e-dev/c/JOSLbot_JFw
In libs2ecore/src/CorePluginInterface.cpp, the function `s2e_tcg_instrument_code()` calls an inline function `tcg_gen_st_i64()`, and this inline function will be eventually replaced with `tcg_gen_op3()`.
The prototype of `tcg_gen_op3()` is from tcg/tcg-op.h, and since CorePluginInterface.cpp includes this header without extern "C", the call to tcg_gen_op3() becomes mangled (i.e. `call _Z11tcg_gen_op39TCGOpcodemmm@plt`), leading to symbol lookup error at runtime.
In tcg/tcg-op.h, conditionally wrap the function prototypes with `extern "C"` when __cplusplus is defined.
> libtcg: fixed symbol lookup error

- klee/lib/Core/ExecutionState.cpp
- klee/lib/Core/Executor.cpp
Hello, Vitaly!
I've spotted code duplication in klee::Executor::fork(), so I tried eliminating them
by reusing the code in klee::ExecutionState::solve().
> klee: Eliminate code duplication in Executor::fork()

- Makefile
www.lua.org has SSL enabled, so we should use it when downloading from their site. Some networks block unencrypted file downloads, so this may be a sticking point for users on those networks. Also, it's generally considered good practice to use SSL whenever available.
> makefile: change lua download link to use SSL

- libs2eplugins/src/s2e/Plugins/ExecutionTracers/InstructionCounter.cpp
This produces bogus data in the trace.
> InstructionCounter: fixed uninitialized variables

- libq/include/qapi/error.h
- libq/src/error.c
The `ERANGE` used in `json-parser.c` is in `errno.h`, which is not included. Found this error when I tried build s2e with debug information. I added the include in `qapi/error.h` and removed the `errno.h` include from `error.c` file.
Signed-off-by: Mingxuan Yao <mingxuanyao@hotmail.com>
> libq: fix the undeclared ERANGE in json-parser

- libs2eplugins/src/s2e/Plugins/PathLimiters/ForkLimiter.cpp
In the current logic, the `maxForkCount` in the ForkLimiter actually allows `maxForkCount+1` forks.
For example, if we set `maxForkCount` to 0, at the first attempt to fork, the following check:
```cpp
m_forkCount[module->Name][curPc] > m_limit
```
, which equals to `0 > 0` is false, so the fork is allowed.
> More accurate maxForkCount in ForkLimiter

- libs2eplugins/src/s2e/Plugins/ExecutionMonitors/LibraryCallMonitor.cpp
- libs2eplugins/src/s2e/Plugins/ExecutionMonitors/LibraryCallMonitor.h
As discussed here (https://groups.google.com/g/s2e-dev/c/KumALD_qpkE), I exposed the `exportName` in the `onLibraryCall` signal.
Even though the signal is not connected by other plugins in this repo, this change may cause an error in end user's local development environment. I can write a function in `LibraryCallMontor`  plugin, which returns `exportName`  given state, module, and target address, as a workaround.
Let me know what you think.
Signed-off-by: Mingxuan Yao <mingxuanyao@hotmail.com>
> libs2eplugins/LibraryCallMonitor: add exportName in onLibraryCall signal

- .github/workflows/build.yaml
- .github/workflows/clang-format.yaml
- Dockerfile
- Makefile
- libs2e/src/CMakeLists.txt
- libs2ecore/src/S2E.cpp
- libs2ecore/src/S2EExecutor.cpp
- libs2eplugins/src/s2e/Plugins/Analyzers/CFIChecker.cpp
- libs2eplugins/src/s2e/Plugins/Core/HostFiles.cpp
- libs2eplugins/src/s2e/Plugins/Core/Vmi.cpp
- libs2eplugins/src/s2e/Plugins/ExecutionTracers/TranslationBlockTracer.cpp
- llvm/Dockerfile
- llvm/Makefile
- llvm/build.sh
- llvm/determine_clang_binary_suffix.py
- llvm/extract-docker.sh
This PR splits LLVM building into a separate makefile.
The main makefile fetches pre-compiled clang/llvm binaries from github release pages.
> Use pre-compiled LLVM

- guest/s2ebios/tests/tests64.asm
- libtcg/src/utils/memalign.c
Module: 
fix missing header and incorrect asm instruction
Description:
Latest update on master branch introduce few of the issues that will prevent users from successfully building the code when running "s2e update && s2e build". The issues are detailed below:
1. the errno is used without correctly including the errno.h header in `libtcg/src/utils/memalign.c`. 
2. In `guest/s2ebios/tests/tests64.asm`, the use of `lea` instruction is in an incorrect way that will cause compilation issue. `lea` (Load Effective Address) instruction in assembly language allows you to perform arithmetic operations while moving data. It's typically used to calculate the addresses of variables. However, in the test file, it's used as `lea rcx, 0x20000` in few of the places. Thus, I tentatively replaced `lea` …
> fix missing header and incorrect asm

- guest/common/include/s2e/opcodes.h
- guest/windows/libcommon/include/s2e/s2e.h
- guest/windows/libcommon/src/amd64/s2e.asm
- guest/windows/libcommon/src/i386/s2e.asm
- guest/windows/libs2e/libs2e.def
- libs2eplugins/src/s2e/Plugins/Core/BaseInstructions.cpp
Hello there, I recently discovered that the i386 asm stub for `S2ESetCpuLogLevel` leads to an unbalanced stack. I figure I should bring it to your attention, although I'm not sure if this function is still actively being used. Thank you.
> Update s2e.asm to fix stack imbalance

- libtcg/include/tcg/utils/osdep.h
_Noreturn fails to compile with gcc (i know, i should use clang)
make LIBTCG_ERROR consistent with QEMU_ERROR
```cc
NORETURN extern void QEMU_ERROR("code path is reachable") qemu_build_not_reached_always(void);
NORETURN extern void LIBTCG_ERROR("code path is reachable") qemu_build_not_reached_always(void);
```
> fix: error: '_Noreturn' does not name a type

- Makefile
- klee/lib/Solver/Z3Solver.cpp
https://github.com/S2E/s2e-env/issues/265
> More dependency fixes and upgrades

- libs2e/src/s2e-kvm.cpp
strtol was always called even if S2E_MAX_PROCESS was not defined causing the preloading of the library to fail due to NULL ptr returned from getenv and passed straight in strtol. Fixed by checking for the correct variable.
> libs2e: bugfix handling of S2E_MAX_PROCESS env

- guest/linux/cgcload/loader.c
- guest/linux/povtest/CMakeLists.txt
Fixed implicit declaration of functions of `read, write, close`.
> guest/linux/cgcload: fixed implicit func decls

- libs2ecore/src/S2EExecutionStateMemory.cpp
The abort was unnecessary. The memory contains concrete data at all times and can be returned as an expression.
> core/memory: fixed crash in single-path mode
